[build-system]
requires = ["setuptools>=42", "wheel", "numpy>= 1.2","scikit-learn==1.0.2","astropy==5.0.3","scipy==1.7.3","peakutils==1.3.3", "progress==1.6","matplotlib==3.5.1","missingpy==0.2.0","optuna==2.10.0","boruta==0.3"]
build-backend = "setuptools.build_meta"